name: Deploy to cPanel

on:
  push:
    branches:
      - prod  # Ce workflow se déclenchera sur chaque push sur la branche `prod`

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Push to cPanel Repository
        run: |
          git remote add cpanel ssh://hibe7449@hibe7449.odns.fr/home/hibe7449/repositories/InvoiceLiveGeneratorPDF
          git push -f cpanel prod
